// <auto-generated />
namespace cbbmsR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class File_Changes_AppFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(File_Changes_AppFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201608150752570_File_Changes_AppFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
