// <auto-generated />
namespace cbbmsR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class image_imageDescription_Change_To_ImageName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_imageDescription_Change_To_ImageName));
        
        string IMigrationMetadata.Id
        {
            get { return "201608140731500_image_imageDescription_Change_To_ImageName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
