// <auto-generated />
namespace cbbmsR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changing_UserID_Type_Int_To_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changing_UserID_Type_Int_To_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201608150831142_Changing_UserID_Type_Int_To_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
