// <auto-generated />
namespace cbbmsR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Minor_changes_to_InventoryItems_Items_Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Minor_changes_to_InventoryItems_Items_Status));
        
        string IMigrationMetadata.Id
        {
            get { return "201608151652405_Minor_changes_to_InventoryItems_Items_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
