// <auto-generated />
namespace cbbmsR3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Images_Changes_To_Files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Images_Changes_To_Files));
        
        string IMigrationMetadata.Id
        {
            get { return "201608150636042_Images_Changes_To_Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
